### ISSUE TITLE
tab button skips non-text fields (e.g. options) in form

### ISSUE THREAD

**Issue by dashmaker** [kobotoolbox/enketo-core#56]
Title says it all. I saw that this was flagged as an issue under enketo-express - issue enketo/enketo#662. It got moved here back in 2014, but this still seems to be an issue and is a major accessibility issue (and time waster as the mouse has to be used to click). Any clues?

**Comment by MartijnR** [comment]
This issue moved back and forth and was duplicated a few times. For Enketo Express you can track it here: https://github.com/kobotoolbox/enketo-express/issues/126

Good news! Last week's (code) update fixed about 80% of these accessibility issues. I am not sure when the new version will be deployed. The remaining issues are planned to be fixed in the next month.
